### ISSUE TITLE
Выражение со скобками для 2-го разработчика

### ISSUE THREAD

**Issue by ProjectVlad2** [Students-of-the-city-of-Kostroma/16VTa#6]
Реализовать к предыдущим действиям работу со скобками ( )
Приступить  к работе сразу после того, как первый разработчик предоставит код с преобразованием строки в обратную польскую запись.

**Comment by Komar1k** [comment]
[Скобки.txt](https://github.com/Students-of-the-city-of-Kostroma/16VTa/files/1998675/default.txt)
